version: "3.9"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "post_db"
      POSTGRES_USER: "stas"
      POSTGRES_PASSWORD: "12345"
    ports:
      - "6000:5432"
networks:
  default:
    # Use a custom driver
    driver: custom-driver-1