create procedure CLEAR_DWH()
    language PLPGSQL
as
$$
declare
begin
    TRUNCATE DBO._CO_NAM_COMPANY_NAME CASCADE;
    TRUNCATE DBO._CO_COT_COMPANY_COUNTRY CASCADE;
    TRUNCATE DBO._CO_COMPANY_NE_ABOUT CASCADE;
    TRUNCATE DBO._CO_COMPANY CASCADE;

    TRUNCATE DBO._COT_COUNTRY CASCADE;
    TRUNCATE DBO._NE_DES_NEWS_DESCRIPTION CASCADE;
    TRUNCATE DBO._NE_IMAGESTORED_UR_AT CASCADE;
    TRUNCATE DBO._NE_NEWS CASCADE;
    TRUNCATE DBO._NE_ORIGINALSTORED_UR_AT CASCADE;
    TRUNCATE DBO._NE_TIT_NEWS_TITLE CASCADE;

    delete from DBO._UR_ADR_URL_ADDRESS;
    delete from DBO._UR_TYP_URL_TYPE;
    delete from DBO._UR_URL;
    delete from DBO._UR_TYP_URL_TYPE;
end;
$$;

alter procedure CLEAR_NEWS() owner to AIRFLOW;

