create or replace procedure DWH.CLEAR_DWH()
    language PLPGSQL
as
$$
declare
begin
    TRUNCATE DWH._CO_NAM_COMPANY_NAME CASCADE;
    TRUNCATE DWH._CO_COT_COMPANY_COUNTRY CASCADE;
    TRUNCATE DWH._CO_COMPANY_NE_ABOUT CASCADE;
    TRUNCATE DWH._CO_COMPANY CASCADE;

    TRUNCATE DWH._COT_COUNTRY CASCADE;
    TRUNCATE DWH._NE_DES_NEWS_DESCRIPTION CASCADE;
    TRUNCATE DWH._NE_IMAGESTORED_UR_AT CASCADE;
    TRUNCATE DWH._NE_NEWS CASCADE;
    TRUNCATE DWH._NE_ORIGINALSTORED_UR_AT CASCADE;
    TRUNCATE DWH._NE_TIT_NEWS_TITLE CASCADE;

    delete from DWH._UR_ADR_URL_ADDRESS;
    delete from DWH._UR_TYP_URL_TYPE;
    delete from DWH._UR_URL;
    delete from DWH._UR_TYP_URL_TYPE;
end;
$$;

