create or replace procedure DWH.CLEAR_DWH()
    language PLPGSQL
as
$$
declare
begin
    TRUNCATE DWH._CO_NAM_COMPANY_NAME CASCADE;
    TRUNCATE DWH._CO_COT_COMPANY_COUNTRY CASCADE;
    TRUNCATE DWH._CO_COMPANY_NE_ABOUT CASCADE;
    TRUNCATE DWH._CO_COMPANY CASCADE;

    TRUNCATE DWH._COT_COUNTRY CASCADE;
    TRUNCATE DWH._NE_DES_NEWS_DESCRIPTION CASCADE;
    TRUNCATE DWH._NE_IMAGESTORED_UR_AT CASCADE;
    TRUNCATE DWH._NE_NEWS CASCADE;
    TRUNCATE DWH._NE_ORIGINALSTORED_UR_AT CASCADE;
    TRUNCATE DWH._NE_TIT_NEWS_TITLE CASCADE;

    TRUNCATE DWH._UR_ADR_URL_ADDRESS CASCADE;
    TRUNCATE DWH._UR_TYP_URL_TYPE CASCADE;
    TRUNCATE DWH._UR_URL CASCADE;
    TRUNCATE DWH._UR_TYP_URL_TYPE CASCADE;

    TRUNCATE DWH._DA_DATE CASCADE;
    TRUNCATE DWH._DA_DAY_DATE_DAY CASCADE;
    TRUNCATE DWH._DA_MON_DATE_MONTH CASCADE;
    TRUNCATE DWH._DA_YER_DATE_YEAR CASCADE;

    TRUNCATE DWH._tr_cls_trade_close CASCADE;
    TRUNCATE DWH._tr_hgh_trade_high CASCADE;
    TRUNCATE DWH._tr_low_trade_low CASCADE;
    TRUNCATE DWH._tr_opn_trade_open CASCADE;
    TRUNCATE DWH._tr_trade CASCADE;

    truncate table DWH._tr_trade_da_when;
    truncate table DWH._co_off_tr_trade;
    truncate table DWH._ne_publish_da_when;
end;
$$;

